import type {
  IdeaBrief,
  PackageEntry,
  ProfileData,
  SkillEntry,
  StatusLabel,
} from './profile.types';

export const STATUS_LABELS: Record<StatusLabel, string> = {
  OPERATIONAL: 'OPERATIONAL',
  SHIPPING: 'SHIPPING',
  BETA: 'BETA',
  BUILDING: 'BUILDING',
  MONITORING: 'MONITORING',
};

export const PROFILE: ProfileData = {
  name: 'John Yaghobieh',
  handle: 'yaghobieh',
  title: 'Full Stack Developer & Team Lead',
  location: 'Tel Aviv, Israel',
  tagline: 'Building the ForgeStack open-source ecosystem — React, TypeScript, Node.js.',
  githubUrl: 'https://github.com/yaghobieh',
  linkedinUrl: 'https://www.linkedin.com/in/johnyaghobieh',
  npmUrl: 'https://www.npmjs.com/~yaghobieh',
  forgeStackUrl: 'https://github.com/yaghobieh?tab=repositories',
  siteUrl: 'https://yaghobieh.github.io/yaghobieh/',
  packageCount: 15,
  repoCount: 27,
  forgeconLevel: 4,
  forgeconLabel: 'FORGECON 4 · ACTIVE DEVELOPMENT · INCREASED BUILD WATCH',
};

export const PACKAGES: PackageEntry[] = [
  {
    id: 'bear',
    name: '@forgedevstack/bear',
    label: 'BEAR',
    description: 'React UI component library with BEM theming and dark mode.',
    layer: 'UI',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/bear',
    githubUrl: 'https://github.com/yaghobieh/bear',
  },
  {
    id: 'grid-table',
    name: '@forgedevstack/grid-table',
    label: 'GRID TABLE',
    description: 'High-performance data grid with sorting, filtering, and virtualization.',
    layer: 'UI',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/grid-table',
    githubUrl: 'https://github.com/yaghobieh/grid-table',
  },
  {
    id: 'synapse',
    name: '@forgedevstack/synapse',
    label: 'SYNAPSE',
    description: 'Lightweight client-side state management for React apps.',
    layer: 'STATE',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/synapse',
    githubUrl: 'https://github.com/yaghobieh/synapse',
  },
  {
    id: 'harbor',
    name: '@forgedevstack/harbor',
    label: 'HARBOR',
    description: 'Backend framework — routes, auth, validation, MongoDB integration.',
    layer: 'BACKEND',
    status: 'SHIPPING',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/harbor',
    githubUrl: 'https://github.com/yaghobieh/Harbor',
  },
  {
    id: 'anvil',
    name: '@forgedevstack/anvil',
    label: 'ANVIL',
    description: 'Utility library — helpers, formatters, and shared primitives.',
    layer: 'UTILS',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/anvil',
    githubUrl: 'https://github.com/yaghobieh/Anvil',
  },
  {
    id: 'aerocraft',
    name: '@forgedevstack/aerocraft',
    label: 'AEROCRAFT',
    description: 'Atomic CSS engine with PostCSS plugin and utility shortcuts.',
    layer: 'STYLING',
    status: 'SHIPPING',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/aerocraft',
    githubUrl: 'https://github.com/yaghobieh/aerocraft',
  },
  {
    id: 'forge-compass',
    name: '@forgedevstack/forge-compass',
    label: 'FORGE COMPASS',
    description: 'Client-side routing for SPA navigation and link handling.',
    layer: 'ROUTING',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/forge-compass',
    githubUrl: 'https://github.com/yaghobieh/compass',
  },
  {
    id: 'forge-form',
    name: '@forgedevstack/forge-form',
    label: 'FORGE FORM',
    description: 'Form state, validation schemas, and field-level error handling.',
    layer: 'FORMS',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/forge-form',
    githubUrl: 'https://github.com/yaghobieh/forge-form',
  },
  {
    id: 'forge-query',
    name: '@forgedevstack/forge-query',
    label: 'FORGE QUERY',
    description: 'Data fetching layer with caching, retries, and query keys.',
    layer: 'DATA',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/forge-query',
    githubUrl: 'https://github.com/yaghobieh/forge-query',
  },
  {
    id: 'forge-cli',
    name: '@forgedevstack/forge-cli',
    label: 'FORGE CLI',
    description: 'Project scaffolding, codegen, and ForgeStack workspace tooling.',
    layer: 'CLI',
    status: 'SHIPPING',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/forge-cli',
    githubUrl: 'https://github.com/yaghobieh/forge-cli',
  },
  {
    id: 'forge-studio',
    name: '@forgedevstack/forge-studio',
    label: 'FORGE STUDIO',
    description: 'AI-assisted component builder and design-to-code pipeline.',
    layer: 'STUDIO',
    status: 'BUILDING',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/forge-studio',
    githubUrl: 'https://github.com/yaghobieh/forge-studio',
  },
  {
    id: 'lintforge',
    name: '@forgedevstack/lintforge',
    label: 'LINTFORGE',
    description: 'Custom ESLint rules enforcing ForgeStack code standards.',
    layer: 'LINT',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/lintforge',
    githubUrl: 'https://github.com/yaghobieh/lintforge',
  },
  {
    id: 'rail',
    name: '@forgedevstack/rail',
    label: 'RAIL',
    description: 'React carousel and slider engine with gesture support.',
    layer: 'UI',
    status: 'SHIPPING',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/rail',
    githubUrl: 'https://github.com/yaghobieh/rail',
  },
  {
    id: 'lingo',
    name: '@forgedevstack/lingo',
    label: 'LINGO',
    description: 'Internationalization and localization for React applications.',
    layer: 'I18N',
    status: 'BETA',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/lingo',
    githubUrl: 'https://github.com/yaghobieh/lingo',
  },
  {
    id: 'kiln',
    name: '@forgedevstack/kiln',
    label: 'KILN',
    description: 'Component documentation and interactive showcase platform.',
    layer: 'DOCS',
    status: 'OPERATIONAL',
    npmUrl: 'https://www.npmjs.com/package/@forgedevstack/kiln',
    githubUrl: 'https://github.com/yaghobieh/kiln',
  },
];

export const IDEAS: IdeaBrief[] = [
  {
    id: 'forge-studio-ai',
    tier: 'HIGH',
    category: 'STUDIO',
    title: 'Forge Studio AI pipeline — design tokens to Bear components',
    summary:
      'End-to-end codegen from Figma exports and natural-language prompts into typed Bear components with Kiln stories.',
    timestamp: '06:14Z',
    signals: 4,
    sources: 2,
  },
  {
    id: 'harbor-auth',
    tier: 'MEDIUM',
    category: 'BACKEND',
    title: 'Harbor unified auth — JWT + OAuth2 plugin architecture',
    summary:
      'Pluggable auth middleware for Harbor services with role-based access and session refresh out of the box.',
    timestamp: '05:42Z',
    signals: 3,
    sources: 3,
  },
  {
    id: 'aerocraft-bear',
    tier: 'MEDIUM',
    category: 'STYLING',
    title: 'AeroCraft × Bear theme bridge — atomic utilities in component SCSS',
    summary:
      'Shared token pipeline so Bear portals consume AeroCraft shortcuts without duplicate CSS bundles.',
    timestamp: '04:18Z',
    signals: 2,
    sources: 2,
  },
  {
    id: 'lingo-portals',
    tier: 'LOW',
    category: 'I18N',
    title: 'Lingo portal sync — single locale bundle across all ForgeStack sites',
    summary:
      'Centralized translation registry with hot-reload for Bear, Grid Table, and AeroCraft portals.',
    timestamp: '03:55Z',
    signals: 2,
    sources: 1,
  },
  {
    id: 'grid-virtual',
    tier: 'HIGH',
    category: 'UI',
    title: 'Grid Table row virtualization — 100k rows at 60fps',
    summary:
      'Windowed rendering with sticky columns and keyboard navigation for enterprise data dashboards.',
    timestamp: '02:30Z',
    signals: 5,
    sources: 4,
  },
  {
    id: 'forge-cli-monorepo',
    tier: 'MEDIUM',
    category: 'CLI',
    title: 'Forge CLI monorepo wizard — scaffold full ForgeStack apps in one command',
    summary:
      'Interactive CLI to bootstrap React + Harbor + Compass + Synapse stacks with LintForge presets.',
    timestamp: '01:07Z',
    signals: 3,
    sources: 2,
  },
];

export const SKILLS: SkillEntry[] = [
  { id: 'react', label: 'React / TypeScript', percent: 95 },
  { id: 'node', label: 'Node.js / Express', percent: 90 },
  { id: 'mongodb', label: 'MongoDB / Mongoose', percent: 85 },
  { id: 'css', label: 'CSS / SCSS / AeroCraft', percent: 88 },
  { id: 'testing', label: 'Testing / CI/CD', percent: 82 },
  { id: 'architecture', label: 'System Architecture', percent: 87 },
  { id: 'leadership', label: 'Team Lead / Mentoring', percent: 92 },
  { id: 'opensource', label: 'Open Source / npm', percent: 94 },
];

export const NAV_LINKS = [
  { id: 'github', label: 'GITHUB', href: PROFILE.githubUrl },
  { id: 'linkedin', label: 'LINKEDIN', href: PROFILE.linkedinUrl },
  { id: 'forgestack', label: 'FORGESTACK', href: PROFILE.forgeStackUrl },
  { id: 'npm', label: 'NPM', href: PROFILE.npmUrl },
] as const;

export const FOOTER_LINKS = [
  { id: 'site', label: 'Live Dashboard', href: PROFILE.siteUrl },
  { id: 'github', label: 'GitHub Profile', href: PROFILE.githubUrl },
  { id: 'npm', label: 'npm Packages', href: PROFILE.npmUrl },
] as const;

export const COLLAGE_TECH = [
  { id: 'react', name: 'React', slug: 'react', brandColor: '61DAFB', category: 'frontend' },
  { id: 'node', name: 'Node.js', slug: 'nodedotjs', brandColor: '339933', category: 'backend' },
  { id: 'mongo', name: 'MongoDB', slug: 'mongodb', brandColor: '47A248', category: 'data' },
  { id: 'docker', name: 'Docker', slug: 'docker', brandColor: '2496ED', category: 'ops' },
  { id: 'kubernetes', name: 'Kubernetes', slug: 'kubernetes', brandColor: '326CE5', category: 'ops' },
  { id: 'jenkins', name: 'Jenkins', slug: 'jenkins', brandColor: 'D24939', category: 'ops' },
  { id: 'vscode', name: 'VS Code', slug: 'visualstudiocode', brandColor: '007ACC', category: 'tools' },
  { id: 'php', name: 'PHP', slug: 'php', brandColor: '777BB4', category: 'backend' },
  { id: 'sql', name: 'SQL', slug: 'postgresql', brandColor: '4169E1', category: 'data' },
  { id: 'css', name: 'CSS', slug: 'css', brandColor: '1572B6', category: 'styling' },
  { id: 'tailwind', name: 'Tailwind', slug: 'tailwindcss', brandColor: '06B6D4', category: 'styling' },
  { id: 'scss', name: 'SCSS', slug: 'sass', brandColor: 'CC6699', category: 'styling' },
] as const satisfies readonly import('./profile.types').CollageTech[];

export const COLLAGE_ICON_BASE = 'https://cdn.simpleicons.org';
